
server:
  port: 8082
spring:
 data:
   mongodb:
     uri: mongodb+srv://sai:saikumar1@cluster0.bbg3l.mongodb.net/CustomerServices?retryWrites=true&w=majority
 application:
   name: customer-service
eureka:
 instance:
   hostname: localhost

