server:
  port: 8006
  
spring:  application:    name: apigateway
  
zuul:  routes:    Admin-Module:
      url: http://localhost:8090
    User-Module:
      url: http://localhost:8091
    room-service:
      url: http://localhost:8083
    reservation-service:
      url: http://localhost:8001
    staff-service:
      url: http://localhost:8080
    